### ISSUE TITLE
building in a CentOS 7 cluster

### ISSUE THREAD

**Issue by mviqm** [LLNL/spheral#101]
I'm building it on a CentOS 7 cluster. All dependencies are ready on a singularity container but I'm having some trouble with MPI not passing the tests. I just introduced the BLT line in CMakeLists and cloned it on the main folder as I thought that would make it but I'm getting still the following error:

[100%] Linking CXX executable ../../tests/testSidreStorage_test
/home/mvi231/Spheral_release/tpl/axom/f209d2f03f002f46be6eb1a7e6aedeb6/lib/libaxom.a(Utilities.cpp.o): In function `axom::utilities::processAbort()':
Utilities.cpp:(.text+0x25): undefined reference to `ompi_mpi_comm_world'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CXXTests/CMakeFiles/testSidreStorage_test.dir/build.make:179: tests/testSidreStorage_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:8472: src/CXXTests/CMakeFiles/testSidreStorage_test.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

I've tried different combinations of -DENABLE_OPENMP and -DENABLE_MPI and some get me to the same error and others to this one:

 -- pip downloading pip-modules
  Could not find a version that satisfies the requirement numpy==1.16.6 (from versions: )
No matching distribution found for numpy==1.16.6
make[2]: *** [CMakeFiles/pip-modules.dir/build.make:82: tpl/cache/.pip-modules_pip_download.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1986: CMakeFiles/pip-modules.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Also,

I have not seen any manual online. From what I have read it uses a python interface which I'm sure I can access through some window system but I also have read it's possible to build a C++ only version. It would be really helpful to see some input files or whatever setup files Spheral may have so I can start wrapping my head around it, and that would make it easier for me to run in the cluster.

**Comment by jmikeowen** [comment]
I don't understand what you mean by introduced the BLT line -- you shouldn't need to change any of the Cmake files.  Did you clone recursively as described on 

https://spheral.readthedocs.io/en/latest/building.html

When you clone it should pull in BLT automatically, and you should be good to go.

**Comment by jmikeowen** [comment]
This is reported to be working now, so closing the issue.
