### ISSUE TITLE
Migrate to LLNL Organization?

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/spheral#12]
Hi @jmikeowen - 

Can we migrate this repo in to the [LLNL organization](https://github.com/llnl) ?

You would still be the admin over the repo, but it would get some increased visibility and redundancy with maintenance.

**Comment by jmikeowen** [comment]
Hmm.  I'm concerned about this being disruptive to the folks working from the repot where it is currently.  I made such a disruptive migration a few years ago going from SourceForge to GitHub, are there GitHub facilities to make such a move less painful to folks who are already using Spheral from this location?

**Comment by IanLee1521** [comment]
Yes, by doing the transfer using the GitHub controls (https://help.github.com/en/github/administering-a-repository/transferring-a-repository), they create a redirect from the old location to the new for both web requests and also git operations:

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. 

We went through this moving several LLNL managed repos under the LLNL org a few years ago, this one must just have been missed.

**Comment by jmikeowen** [comment]
What is the maintenance advantage?

**Comment by IanLee1521** [comment]
It makes it easier to incorporate the project in with other lab projects, such as on software.llnl.gov, and to answer questions about the Lab's projects. Also, if there are ever any issues with the repo and you are unavailable, then the organization admins can help get them sorted.

**Comment by tgamblin** [comment]
@jmikeowen: in case it wasn't clear above, people using the old URL for this repo would be seamlessly redirected to the new one, so they do not need to change their workflow.

I moved this repo years ago and you can still go to the old URL and land on the new repo in the LLNL organization: http://github.com/tgamblin/muster.  Cloning the old URL still works as well.

The main thing this would help us do is show off LLNL open source codes like Spheral in one place.

**Comment by jmikeowen** [comment]
Sorry, I'm buried in various things right now so this percolates along slowly.  I'd suggest maybe we start with the PYB11Generator repository since that's a much smaller, less active thing right now:

https://github.com/jmikeowen/PYB11Generator

I'll only have to notify a few folks about migrating that one, so we can see how it goes.  I also have another project about ready to release as well, so maybe we can just start that one in this place?

**Comment by IanLee1521** [comment]
No worries, things move at a different pace now for sure.

Yes, new projects should definitely start on the LLNL org, which is what IM will tell you when you get your release approved. 

We can certainly start with that other project. The process there is to start with getting you in the organization. Just for records, can you shoot me an email from your lab email address, and I'll send you the invite link? Then you'll be able to follow the transfer instructions I linked above.

**Comment by jmikeowen** [comment]
Done.
