### ISSUE TITLE
ANEOS standard material parameters not available with new Spack TPL build

### ISSUE THREAD

**Issue by jmikeowen** [LLNL/spheral#144]
The file "src/SolidMaterial/ShadowANEOS.py.in" provides some convenient constructors for building the ANEOS equation of state.  One of these features is the ability to specify one of the built in materials (quartz, dunnite, or serpentine), which use data files installed during our TPL build of ANEOS.  It appears those files are being installed in the ANEOS directory OK, but the Cmake variable @ANEOS_INPUT_DEST_DIR@ is not being set correctly when installing ShadowANEOS.py.

**Comment by mdavis36** [comment]
I think that was accidentally ripped out in the recent build system cleanup. We should be able to add `set(ANEOS_INPUT_DEST_DIR "${${lib_name}_DIR}/input")` back into `cmake/tpl/aneos.cmake` to fix this.

**Comment by jmikeowen** [comment]
Resolved in commit [2ea372a]

https://github.com/LLNL/spheral/commit/2ea372a15aa2132cfacd668bd8e7e7ff8166f934
