### ISSUE TITLE
HDF5 Error in running the spheral

### ISSUE THREAD

**Issue by Cal-tr** [LLNL/spheral#169]
I have built and installed the SPHERAL outside of LLNL following the guidance in https://spheral.readthedocs.io/en/latest/.
When I input " ./spheral tests/functional/Strength/TaylorImpact/TaylorImpact.py" to run the demo in spheral, the following error information was printed:
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Edeprec.c line 468 in H5Eset_auto1(): library initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #001: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5.c line 210 in H5_init_library(): unable to initialize dataset interface
    major: Function entry/exit
    minor: Unable to initialize object
  #002: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Dint.c line 141 in H5D_init(): interface initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #003: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Dint.c line 183 in H5D__init_interface(): can't get default dataset creation property list
    major: Dataset
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5P.c line 297 in H5Pcreate(): not a property list class
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pfapl.c line 1326 in H5Pset_fclose_degree(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pint.c line 3379 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pint.c line 3329 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pfapl.c line 1043 in H5Pset_cache(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pint.c line 3379 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5Pint.c line 3329 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: /home/cal/Desktop/SPHERAL/spheral-spack-tpls/builds/spack-stage-hdf5-1.8.19-kplx2jxzsjewu45wywxildj5yd23yk4q/spack-src/src/H5P.c line 1474 in H5Pclose(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
DBCreate: Low-level function call failed: Problem setting HDF5 VFD options
Traceback (most recent call last):
  File "tests/functional/Strength/TaylorImpact/TaylorImpact.py", line 542, in <module>
    vizTime = vizTime)
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 117, in __init__
    facetedBoundaries = facetedBoundaries)
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 252, in reinitializeProblem
    self.doPeriodicWork(force=True)
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 399, in doPeriodicWork
    method(self.totalSteps, t1, dt)
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 501, in updateRestart
    self.dropRestartFile()
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 560, in dropRestartFile
    file = self.restartFileConstructor(fileName, Create)
RuntimeError: Verification failed: SiloFileIO ERROR: unable to open dumps-TaylorImpact/2d/SPH/gradh=True/XSPH=True/reflect=True/10x80/procs=1/restarts/proc-0000/TaylorImpact-10-80_cycle0.silo
...at line 348 of file /home/cal/Desktop/SPHERAL/spheral/src/FileIO/SiloFileIO.cc.

I have read the code in SpheralController.py, in line 31:
restartFileConstructor = SiloFileIO,
the class SiloFileIO is not defined and used in the constructor(I think the lack of the member variable lead to the error in HDF5).
The prefix "/.venv/bin/ats" is also used to run the demo and all of the tests failed as well because of the error in HDF5.

Moreover, I copy the python files in "spheral/src/Pybind11Wraps/FileIO" to "spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral" and insert "from SiloFileIO import SiloFileIO" at the top of SpheralController.py so that the program could recognize this class.
I ran the aforementioned code again, and the following error information is printed:
Traceback (most recent call last):
  File "tests/functional/Strength/TaylorImpact/TaylorImpact.py", line 48, in <module>
    from Spheral import *
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/Spheral.py", line 97, in <module>
    from SpheralController import *
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SpheralController.py", line 13, in <module>
    from SiloFileIO import SiloFileIO
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/SiloFileIO.py", line 5, in <module>
    from FileIO import *
  File "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake_avx512-gcc/install/.venv/lib/python2.7/site-packages/Spheral/FileIO.py", line 4, in <module>
    from PYB11Generator import *
ImportError: No module named PYB11Generator

The python package PYB11Generator can not be recognized.
I wonder whether I have built and installed the SPHERAL in the right way. Otherwise, why I can not recognize the class and package which were defined and complied with in the previous?

**Comment by mdavis36** [comment]
Your initial errors look like an issue with the underlying HDF5 installation. This is hard to diagnose, without time and access to your system, but it looks like everything built and installed fine. With a clen installation can you run ``./spheral -c "import Spheral"`` this is a basic smoketest. You could also try ``./spheral-atstest test/integration.ats`` to run our full test suite.

We do also a docker build of spheral https://github.com/LLNL/spheral/pkgs/container/spheral that you can try. This is a really easy way to get started with spheral if you are having system configuration issues.

**Comment by Cal-tr** [comment]
I appreciate that you share the docker build. It helped me a lot to locate the error and get started with spheral. My problem was solved by updating the version of CMake. Best Wishes.

**Comment by mdavis36** [comment]
Glad you were able to resolve the issue, what version of CMake were you using before?

**Comment by Cal-tr** [comment]
> Glad you were able to resolve the issue, what version of CMake were you using before?

I have updated the CMake from 3.16.3 to 3.24.1. Moreover, the CMake 3.16.3 was installed default by Ubuntu 20.04 which I downloaded the iso from https://old-releases.ubuntu.com/releases/20.04/
