### ISSUE TITLE
Silo File Reading Error using VisIt

### ISSUE THREAD

**Issue by Cal-tr** [LLNL/spheral#174]
Thanks to the docker build of spheral https://github.com/LLNL/spheral/pkgs/container/spheral,  I have run the tests(./tests/integration.ats) successfully with PASS.

I am interested in the binary asteroid system and the Double Asteroid Redirection Test. The impactor successfully impacted its asteroid target on Monday, September 26 at 7:14 p.m. EDT. Italian Space Agency’s LICIACube captured the image of the ejecta. I wonder about the hypervelocity impact processes and the crater formation. I have read the article "Benchmarking impact hydrocodes in the strength regime: Implications for modeling deflection by a kinetic impactor". The open-source Adaptive Smoothed Particle Hydrodynamics (ASPH) code Spheral impressed me due to the excellent comparison.

Therefore, I run the scripts ./tests/functional/Strength/TaylorImpact/TaylorImpact.py and ./tests/functional/Strength/PlateImpact/TP106-1d.py which I think are similar to the hypervelocity impact processes.

The scripts wrote the output file in .silo. Hence, I try to use the visualization tool VisIt https://visit-dav.github.io/visit-website/ to process Silo data. I confirm that I have successfully installed the software on the basis of the data provided in VisiIt. Meanwhile, it seems that the silo file generated by TaylorImpact.py can be opened successfully(Part of the plots can be drawn).

However, there are some problems happened in opening the silo file generated by TP106-1d.py:
VisIt could not read from the file "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake-gcc+mpi/install/dumps-TP106-1d/strength=True/SPH/densityUpdate=MassDensityType.IntegrateDensity/nxAl=100_nxTa=597/restarts/TP106-697_cycle3000.silo".
The generated error message was:
There was an error opening /home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake-gcc+mpi/install/dumps-TP106-1d/strength=True/SPH/densityUpdate=MassDensityType.IntegrateDensity/nxAl=100_nxTa=597/restarts/TP106-697_cycle3000.silo. It may be an invalid file.  VisIt tried using the following file format readers to open the file: Silo
The following error(s) may be helpful in identifying the problem:
Although VisIt has opened the file, "/home/cal/Desktop/SPHERAL/spheral/build_linux-ubuntu20.04-skylake-gcc+mpi/install/dumps-TP106-1d/strength=True/SPH/densityUpdate=MassDensityType.IntegrateDensity/nxAl=100_nxTa=597/restarts/TP106-697_cycle3000.silo",
no data was found in the file for VisIt to work with.

**Comment by jmikeowen** [comment]
The 1D tests do not produce output that can be parsed with Visit. Those are instead plotted using Gnuplot, matplotlib, etc.
