### ISSUE TITLE
Name/Import/Type Error in running tests scripts

### ISSUE THREAD

**Issue by Cal-tr** [LLNL/spheral#175]
The ATS tests in ./tests/integration.ats were passed in the docker build of spheral https://github.com/LLNL/spheral/pkgs/container/spheral.

Moreover, I try to run the test scripts which are not included in the integration.ats. There are some problems in running the test scripts. I catalog them into three groups: NameError, Import Error, and Type Error.

NameError: name 'XXX' is not defined.
Where XXX refers to some variables or classes, such as AsphSolidNodeList, SolidSPHHydro, and SphNodeList3d in ExpandingTube-3d.py, PlateImpact-1d.py, and Zeldovich-pancake-SPH.py, respectively.

ImportError: No module named XXX.
Where XXX refers to some modules or packages, such as loadmpi, Numeric, and SolidSpheral in Noh-spherical-3d-benchmark.py, ExpandingTube-rz.py, and TensileDisk-GradyKipp-2d.py, respectively.

TypeError: XXXX got an unexpected keyword argument YYYY.
Where XXXX and YYYY refer to some functions and parameters, such as SPH() ->  'negativePressureInDamage', centroidalRelaxNodes() -> 'fracTol', and makeFluidNodeList2d() -> 'topGridCellSize' in TensileRod-2d.py, centroidalRelaxation-2d.py, and testMedialGenerator2d.py.

**Comment by jmikeowen** [comment]
There are many scripts in the tests/ directory which are historical.  They have not been kept up to date with the current interface and therefore do not currently run.  We keep them around in case we want to go back and run them again (after updating), but for now the only scripts that are guaranteed to work are the ones being tested in the ATS testing suite.

**Comment by jmikeowen** [comment]
See comment above, it is expected many of these older examples do not run if they're not in the test suite.
