### ISSUE TITLE
What is "aneos" dependency?

### ISSUE THREAD

**Issue by yurivict** [LLNL/spheral#187]
Repology finds [nothing](https://repology.org/projects/?search=aneos).
The [M-ANEOS](https://github.com/isale-code/M-ANEOS) project installs only one executable, and spheral is looking for a shared library.

**Comment by mdavis36** [comment]
Spheral looks for `libaneos.a`, Spheral uses spack to install all of our TPLs and M-ANEOS has a custom spack recipe we use to build and install it properly `scripts/spack/packages/m-aneos/package.py`.

**Comment by yurivict** [comment]
Currently [Spack](https://packages.spack.io/) doesn't have ports for ```spheral``` or ```aneos```.

Is this expected?

**Comment by mdavis36** [comment]
The Spheral spack packge has not been upstreamed to spack as it is still a work in progress. We use spack through a few convenience scripts to build allof our tpls. We have documentation on how to build all of our tpls and spheral here https://spheral.readthedocs.io/en/latest/index.html.

**Comment by yurivict** [comment]
Thank you.
