### ISSUE TITLE
Gnuplot not found

### ISSUE THREAD

**Issue by Edithnuaa** [LLNL/spheral#216]
When I tried to run tests/functional/Strength/PlateImpact/TP106-1d.py, the error "Gnuplot not found" appeared.

I found the Gnuplot package in install/lib/python2.7/site-packages/Gnuplot, and the same error appeared when I running demo.py within the package by command `python demo.py`.

It seems that the Gnuplot package wasn't installed correctly.

**Comment by mdavis36** [comment]
gnuplot has been deprecated from spheral as of the python3 PR that is now in develop. There are also a number of tests that are deprecated which contunue to live in the repo for reference purposes, but not all are regularly tested. For a list of working test files I suggest you look at `tests/integration.ats`.
