### ISSUE TITLE
Runtime Problem of the parallel Compution

### ISSUE THREAD

**Issue by Cal-tr** [LLNL/spheral#217]
When I import the spheral package, the flowing information is printed:
/------------------------------------------------------------------------------\
|  Spheral version             : HEAD 6336794cf 7994                           |
|    number of MPI tasks       : 1                                             |
|    number of threads per rank: 4                                             |
\------------------------------------------------------------------------------/
and my program can be run successfully. The utilization of CPU can achieve 100%.

Then, I change the number of thread of my computer,  the flowing information is printed:
/------------------------------------------------------------------------------\
|  Spheral version             : HEAD 6336794cf 7994                           |
|    number of MPI tasks       : 1                                             |
|    number of threads per rank: 256                                             |
\------------------------------------------------------------------------------/
The utilization of CPU can achieve 100% as well. However, the running speed of my program get extremely slow.
I wonder the reason of the degradation of the running speed, for example, the deep copy of the array in the "threadCopy" function.

**Comment by mdavis36** [comment]
Using the maximum number of threads does not always correlate to the fastest results. 256 is a considerable number and yes deep copies along with lock regions that exist in the code will contribute to this. I've found that 4, 8 and 16 OpenMP threads usually produce the best speedups when they are attainable. Spheral has active development for GPU and better multi-threaded optimization but there is still much work to do.
