### ISSUE TITLE
ImportError: Python version mismatch

### ISSUE THREAD

**Issue by Edithnuaa** [LLNL/spheral#221]
I try to install Spheral on my the other computer. The installation went well without error. But when I ran the test command `./spheral -c "import Spheral" `, there was no output. 

I tried to run `./spheral Spheral/Spheral.py`, the error showed below: 
```
ImportError: Python version mismatch: module was compiled for Python 3.10, but the interpreter version is incompatible: 3.9.10 (main, May 23 2023, 12:55:28) 
[GCC 11.3.0].
```

The error is clear that the python used for compiling module is not the same python that used as the interpreter. 

**SYSTEM:** 
VM Ubuntu 22.02 on MacOS 13.4 Ventura
**DEFAULT PYTHON VERSION:** 
Python3 stands for Python3.10, Python2 stands for Python2.7
**GCC VERSION:** 
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

I have tried to re-install Spheral and it didn't work out.

**Comment by mdavis36** [comment]
Closing as this seems to be an environment issue. Can re-open is further investigation is needed.
