### ISSUE TITLE
Improve CMake export target

### ISSUE THREAD

**Issue by ldowen** [LLNL/spheral#266]
A few more things need to exported:

- [x] The `python_DIR` when the build is `ENABLE_STATIC_CXXONLY=FALSE`
- [x] The CMake compiler paths
- [x] The MPI paths

**Comment by mdavis36** [comment]
Passing out the python_DIR makes sense to me. I don't understand why we are passing the compiler and MPI paths. Those should be handled by the CMake project that is a user of Spheral

**Comment by ldowen** [comment]
It would only be exported in a way that SpheralC can use it. Right now, those things are set by the TPL manager for Spheral, and SpheralC has no way of knowing those things. Otherwise, it would just rely on having the correct modules loaded.

**Comment by mdavis36** [comment]
@ldowen Is this good to close?
