### ISSUE TITLE
Make GSPH package optional

### ISSUE THREAD

**Issue by adayton1** [LLNL/spheral#292]
GSPH is pretty much self contained except that FSISPH includes two files from GSPH.

#include "GSPH/computeSPHVolume.hh"
#include "GSPH/Policies/ReplaceWithRatioPolicy.hh"

Both files are pretty small and neither depend on anything else in GSPH. Can they be moved to some location where they can be shared? That would allow GSPH to be made an optional package.

**Comment by jmikeowen** [comment]
Both those packages (FSI and GSPH) are Jason Pearl's (@jmpearl ), so I'd suggest talk with Jason.
