### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by Kulitorum** [LLNL/spheral#38]
The build folders have .vcxproj files, but no common sln file.

Does an sln file exist, can you upload it?

Thank you.

**Comment by jmikeowen** [comment]
Those Windows visual studio project files are from some other folks that have been experimenting with building portions of Spheral on Windows, not the full code.  There isn't more available at the moment I believe.  For building on Windows using WSL (WSL2 is best) has been working.

So the short answer is those VS project files are currently not a supported method of building Spheral.
