### ISSUE TITLE
System crashed when installing Spheral

### ISSUE THREAD

**Issue by jiaoyf16** [LLNL/spheral#46]
Thanks for recent updates of Spheral. But when I'm installing it on my Ubuntu 20.10, something unknown caused the system crashed, for several times. Refer to https://spheral.readthedocs.io/en/latest/building.html.

**Comment by jmikeowen** [comment]
I don't understand, are you saying building/installing Spheral caused your Ubuntu system to crash?  That certainly should never happen.  My only guess would be perhaps you don't have enough memory available for the compile: some of the Python binding modules in particular use a lot of memory while building.  I'd suggest try on another machine, and check how much memory is available.
