### ISSUE TITLE
Can you install it in Windows system? Thank you

### ISSUE THREAD

**Issue by yufeifeiyu** [LLNL/spheral#51]

**Comment by mdavis36** [comment]
We do not currently have native Windows support. However Spheral can be instaled through Windows Subsystem Linux. We recommend WSL2. The WSL2 Spheral installation process is the same as on Linux. Configurations for the subsystem are detinled in the installation documentation [here](https://spheral.readthedocs.io/en/latest/building.html).

**Comment by yufeifeiyu** [comment]
ths
